import { ChevronLeft, ChevronRight } from 'lucide-react'
import IconButton from '../common/IconButton.jsx'
import { formatCurrency } from '../../utils/formatCurrency.js'
import { utcDateKey } from '../../utils/performanceAnalytics.js'

const weekdays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
function TradingCalendar({ dailyResults, month, onMonthChange }) {
  const year = month.getUTCFullYear(), monthIndex = month.getUTCMonth(), first = new Date(Date.UTC(year, monthIndex, 1)), days = new Date(Date.UTC(year, monthIndex + 1, 0)).getUTCDate(), leading = (first.getUTCDay() + 6) % 7
  const results = new Map(dailyResults.map((item) => [item.date, item])); const move = (amount) => onMonthChange(new Date(Date.UTC(year, monthIndex + amount, 1))); const today = () => { const now = new Date(); onMonthChange(new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1))) }
  return <div><div className="flex flex-col justify-between gap-3 border-b border-border px-5 py-4 sm:flex-row sm:items-center"><div><h2 className="text-sm font-semibold">Trading calendar</h2><p className="mt-1 text-xs text-muted">Realized P/L by UTC close date</p></div><div className="flex items-center gap-2"><button className="h-8 rounded-lg px-2 text-xs font-semibold text-accent hover:bg-accent/10" onClick={today} type="button">Today</button><IconButton aria-label="Previous month" icon={ChevronLeft} onClick={() => move(-1)} size="sm" /><p className="w-28 text-center text-xs font-semibold">{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric', timeZone: 'UTC' })}</p><IconButton aria-label="Next month" icon={ChevronRight} onClick={() => move(1)} size="sm" /></div></div><div className="grid grid-cols-7 border-b border-border px-3 py-2">{weekdays.map((day) => <p className="text-center text-[10px] font-semibold uppercase text-muted" key={day}>{day}</p>)}</div><div className="grid grid-cols-7 gap-px bg-border">{Array.from({ length: leading + days }, (_, index) => { if (index < leading) return <span className="min-h-20 bg-surface" key={`blank-${index}`} />; const day = index - leading + 1, date = new Date(Date.UTC(year, monthIndex, day)), result = results.get(utcDateKey(date)); return <div className={`min-h-20 min-w-0 bg-surface p-1.5 sm:p-2 ${result?.pnl > 0 ? 'bg-positive/5' : result?.pnl < 0 ? 'bg-negative/5' : ''}`} key={day}><p className="text-[10px] text-muted">{day}</p>{result && <><p className={`financial-value mt-2 truncate text-[10px] font-semibold sm:text-[11px] ${result.pnl >= 0 ? 'text-positive' : 'text-negative'}`}>{formatCurrency(result.pnl)}</p><p className="mt-1 truncate text-[9px] text-muted">{result.closes} {result.closes === 1 ? 'close' : 'closes'}</p></>}</div> })}</div></div>
}
export default TradingCalendar
