import { useMemo, useState } from 'react'
import { BarChart3, CalendarDays, CircleDollarSign, Gauge, Trophy } from 'lucide-react'
import Card from '../components/common/Card.jsx'
import PageHeader from '../components/common/PageHeader.jsx'
import Select from '../components/common/Select.jsx'
import PerformanceChart from '../components/charts/PerformanceChart.jsx'
import TradingCalendar from '../components/charts/TradingCalendar.jsx'
import useRisk from '../hooks/useRisk.js'
import { formatCurrency } from '../utils/formatCurrency.js'
import { buildMarketBreakdown, buildRealizedPnlSeries } from '../utils/tradeAnalytics.js'
import { aggregatePerformance, currentUtcPeriods, filterTrades } from '../utils/performanceAnalytics.js'

const initialFilters = { range: 'all', market: 'all', assetClass: 'all' }
function Analytics() {
  const { trades } = useRisk()
  const [filters, setFilters] = useState(initialFilters)
  const [month, setMonth] = useState(() => new Date(Date.UTC(new Date().getUTCFullYear(), new Date().getUTCMonth(), 1)))
  const markets = useMemo(() => [...new Set(trades.map((trade) => trade.symbol))].sort(), [trades])
  const filtered = useMemo(() => filterTrades(trades, filters), [filters, trades])
  const analytics = useMemo(() => aggregatePerformance(filtered), [filtered])
  const periods = useMemo(() => currentUtcPeriods(filtered), [filtered])
  const series = useMemo(() => buildRealizedPnlSeries(filtered), [filtered])
  const breakdown = useMemo(() => buildMarketBreakdown(filtered), [filtered])
  const change = (field) => (event) => setFilters((current) => ({ ...current, [field]: event.target.value }))
  const factor = analytics.profitFactor === Infinity ? '∞' : analytics.profitFactor.toFixed(2)
  const cards = [['Realized P/L', formatCurrency(analytics.realizedPnl), CircleDollarSign], ['Realized performance drawdown', formatCurrency(analytics.currentDrawdown), Gauge], ['Maximum realized drawdown', formatCurrency(analytics.maximumDrawdown), Gauge], ['Win rate', `${analytics.winRate.toFixed(2)}%`, Trophy], ['Profit factor', factor, BarChart3]]
  return <div className="space-y-6"><PageHeader description="UTC-consistent intelligence from completed simulated executions." eyebrow="Performance intelligence" title="Analytics" />
    <Card><div className="grid gap-3 sm:grid-cols-3"><Select label="Period" onChange={change('range')} value={filters.range}><option value="all">All time</option><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option></Select><Select label="Market" onChange={change('market')} value={filters.market}><option value="all">All markets</option>{markets.map((market) => <option key={market} value={market}>{market}</option>)}</Select><Select label="Asset class" onChange={change('assetClass')} value={filters.assetClass}><option value="all">All classes</option><option value="crypto">Crypto</option><option value="forex">Forex</option><option value="gold">Gold</option></Select></div></Card>
    <section aria-label="Performance summary" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label, value, Icon]) => <Card key={label}><Icon className="size-5 text-accent" /><p className="mt-4 text-xs text-muted">{label}</p><p className="financial-value mt-2 text-xl font-semibold">{value}</p>{label === 'Realized performance drawdown' && <p className="mt-1 text-[10px] text-muted">Peak: {formatCurrency(analytics.realizedPeak)}</p>}</Card>)}</section>
    <div className="grid gap-4 lg:grid-cols-3">{[['Today', periods.today], ['This week', periods.week], ['This month', periods.month]].map(([label, value]) => <Card key={label}><p className="text-xs font-semibold">{label}</p><p className={`financial-value mt-3 text-lg font-semibold ${value.realizedPnl >= 0 ? 'text-positive' : 'text-negative'}`}>{formatCurrency(value.realizedPnl)}</p><dl className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><div><dt className="text-muted">Fees</dt><dd className="financial-value mt-1">{formatCurrency(value.fees)}</dd></div><div><dt className="text-muted">Trades</dt><dd className="financial-value mt-1">{value.tradeCount}</dd></div><div><dt className="text-muted">Winning closes</dt><dd className="financial-value mt-1 text-positive">{value.wins}</dd></div><div><dt className="text-muted">Losing closes</dt><dd className="financial-value mt-1 text-negative">{value.losses}</dd></div></dl><p className="mt-3 text-[10px] text-muted">UTC · Week begins Monday</p></Card>)}</div>
    <div className="grid min-w-0 gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(18rem,0.7fr)]"><Card padding="none"><PerformanceChart data={series} /></Card><Card padding="none"><div className="border-b border-border px-5 py-4"><h2 className="text-sm font-semibold">Quality metrics</h2><p className="mt-1 text-xs text-muted">Filtered completed SELL outcomes</p></div><dl className="divide-y divide-border">{[['Winning closes', analytics.wins], ['Losing closes', analytics.losses], ['Average win', formatCurrency(analytics.averageWin)], ['Average loss', formatCurrency(analytics.averageLoss)], ['Largest win', analytics.largestWin === null ? 'Unavailable' : formatCurrency(analytics.largestWin)], ['Largest loss', analytics.largestLoss === null ? 'Unavailable' : formatCurrency(analytics.largestLoss)], ['Current win streak', analytics.currentWinStreak], ['Current loss streak', analytics.currentLossStreak], ['Longest win streak', analytics.longestWinStreak], ['Longest loss streak', analytics.longestLossStreak], ['Fees', formatCurrency(analytics.fees)], ['Volume', formatCurrency(analytics.volume)]].map(([label, value]) => <div className="flex justify-between gap-4 px-5 py-3" key={label}><dt className="text-xs text-muted">{label}</dt><dd className="financial-value text-sm font-semibold">{value}</dd></div>)}</dl></Card></div>
    <div className="grid gap-4 sm:grid-cols-2"><Card><CalendarDays className="size-5 text-positive" /><p className="mt-4 text-xs text-muted">Best UTC day</p><p className="mt-2 text-sm font-semibold">{analytics.bestDay ? `${analytics.bestDay.date} · ${formatCurrency(analytics.bestDay.pnl)}` : 'Unavailable'}</p>{analytics.bestDay && <p className="mt-1 text-xs text-muted">{analytics.bestDay.closes} completed {analytics.bestDay.closes === 1 ? 'close' : 'closes'}</p>}</Card><Card><CalendarDays className="size-5 text-negative" /><p className="mt-4 text-xs text-muted">Worst UTC day</p><p className="mt-2 text-sm font-semibold">{analytics.worstDay ? `${analytics.worstDay.date} · ${formatCurrency(analytics.worstDay.pnl)}` : 'Unavailable'}</p>{analytics.worstDay && <p className="mt-1 text-xs text-muted">{analytics.worstDay.closes} completed {analytics.worstDay.closes === 1 ? 'close' : 'closes'}</p>}</Card></div>
    <Card padding="none"><TradingCalendar dailyResults={analytics.days} month={month} onMonthChange={setMonth} /></Card>
    <Card padding="none"><div className="border-b border-border px-5 py-4"><h2 className="text-sm font-semibold">Performance by market</h2></div>{breakdown.length ? <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead className="border-b border-border bg-elevated/40 text-[10px] uppercase tracking-wider text-muted"><tr><th className="px-5 py-3">Market</th><th className="px-5 py-3">Trades</th><th className="px-5 py-3">Volume</th><th className="px-5 py-3">Realized P/L</th></tr></thead><tbody className="divide-y divide-border">{breakdown.map((row) => <tr key={row.symbol}><td className="px-5 py-4 text-sm font-semibold">{row.symbol}</td><td className="financial-value px-5 py-4 text-sm">{row.trades}</td><td className="financial-value px-5 py-4 text-sm">{formatCurrency(row.volume)}</td><td className={`financial-value px-5 py-4 text-sm ${row.realizedPnl >= 0 ? 'text-positive' : 'text-negative'}`}>{formatCurrency(row.realizedPnl)}</td></tr>)}</tbody></table></div> : <p className="p-8 text-center text-sm text-muted">No activity matches these filters.</p>}</Card>
  </div>
}
export default Analytics
