import { useEffect, useMemo, useState } from 'react'
import { CircleAlert, Download, FlaskConical, LoaderCircle, Save, Trash2 } from 'lucide-react'
import BacktestEquityChart from '../components/charts/BacktestEquityChart.jsx'
import MarketReplay from '../components/backtest/MarketReplay.jsx'
import Badge from '../components/common/Badge.jsx'
import Button from '../components/common/Button.jsx'
import Card from '../components/common/Card.jsx'
import Input from '../components/common/Input.jsx'
import Modal from '../components/common/Modal.jsx'
import PageHeader from '../components/common/PageHeader.jsx'
import Select from '../components/common/Select.jsx'
import { TRADING_FEE_RATE } from '../constants/trading.js'
import { marketBySymbol, markets } from '../data/markets.js'
import useAuth from '../hooks/useAuth.js'
import { deleteSavedBacktest, loadBacktestCandles, saveBacktest, subscribeToSavedBacktests } from '../services/backtestService.js'
import { runBacktest, STRATEGIES, validateBacktestConfiguration } from '../utils/backtestEngine.js'
import { downloadCsv } from '../utils/csv.js'
import { formatCurrency } from '../utils/formatCurrency.js'
import { formatPrice } from '../utils/marketFormatters.js'

const intervals = ['1m', '5m', '15m', '1h', '4h', '1d']
const initialConfig = { symbol: 'BTCUSDT', interval: '1h', strategy: 'ma', strategyParameters: { ...STRATEGIES.ma.defaults }, startingBalance: 10000, sizingMode: 'percent', positionSize: 25, slippage: 0, stopLossPercent: '', takeProfitPercent: '' }
const dateTime = (time) => new Date(time * 1000).toLocaleString()
const factor = (value) => value === null || value === undefined ? '∞' : Number(value).toFixed(2)

function Backtest() {
  const { currentUser } = useAuth()
  const [config, setConfig] = useState(initialConfig), [result, setResult] = useState(null), [running, setRunning] = useState(false)
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [saveName, setSaveName] = useState('')
  const [saved, setSaved] = useState([]), [selected, setSelected] = useState([]), [summary, setSummary] = useState(null), [tradeDetail, setTradeDetail] = useState(null), [deleteTarget, setDeleteTarget] = useState(null)
  useEffect(() => subscribeToSavedBacktests(currentUser.uid, setSaved, () => setError('Saved backtests are unavailable until the latest Firestore rules and index are deployed.')), [currentUser.uid])
  const market = marketBySymbol.get(config.symbol)
  const resultMarket = result ? marketBySymbol.get(result.configuration.symbol) : null

  const execute = async (nextConfig = config) => {
    const validation = validateBacktestConfiguration(nextConfig)
    if (validation) { setError(validation); return }
    setRunning(true); setError(''); setNotice('')
    try {
      const candles = await loadBacktestCandles(nextConfig.symbol, nextConfig.interval)
      const output = runBacktest(candles, { ...nextConfig, feeRate: TRADING_FEE_RATE })
      setConfig(nextConfig); setResult({ ...output, runId: `${Date.now()}-${nextConfig.symbol}-${nextConfig.interval}` })
      const first = new Date(output.candles[0].time * 1000).toLocaleString(), last = new Date(output.candles.at(-1).time * 1000).toLocaleString()
      setNotice(`${output.metrics.candlesTested} actual provider candles tested · ${first} to ${last}`)
    } catch (requestError) { setError(requestError?.message || 'Historical data is unavailable. Please try again later.') }
    finally { setRunning(false) }
  }
  const update = (field) => (event) => setConfig((current) => ({ ...current, [field]: event.target.value }))
  const updateParameter = (field) => (event) => setConfig((current) => ({ ...current, strategyParameters: { ...current.strategyParameters, [field]: event.target.value } }))
  const changeStrategy = (event) => { const strategy = event.target.value; setConfig((current) => ({ ...current, strategy, strategyParameters: { ...STRATEGIES[strategy].defaults } })) }
  const save = async () => { if (!result) return; try { await saveBacktest(currentUser.uid, saveName, marketBySymbol.get(result.configuration.symbol), result); setSaveName(''); setNotice('Backtest summary saved.') } catch (requestError) { setError(requestError?.message || 'Unable to save this backtest.') } }
  const rerun = (item) => { const next = { symbol: item.symbol, interval: item.interval, strategy: item.strategy, strategyParameters: item.strategyParameters, startingBalance: item.configuration.startingBalance, sizingMode: item.configuration.sizingMode, positionSize: item.configuration.positionSize, slippage: item.configuration.slippage, stopLossPercent: item.configuration.stopLossPercent ?? '', takeProfitPercent: item.configuration.takeProfitPercent ?? '' }; execute(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const exportCsv = () => result && downloadCsv(`tradepilot-backtest-${result.configuration.symbol}-${result.configuration.interval}.csv`, ['Trade Number', 'Symbol', 'Strategy', 'Entry Time', 'Entry Price', 'Exit Time', 'Exit Price', 'Quantity', 'Entry Fee', 'Exit Fee', 'Net P&L', 'Return %', 'Exit Reason'], result.trades.map((trade, index) => [index + 1, result.configuration.symbol, STRATEGIES[result.configuration.strategy].label, new Date(trade.entryTime * 1000).toISOString(), trade.entryPrice, new Date(trade.exitTime * 1000).toISOString(), trade.exitPrice, trade.quantity, trade.entryFee, trade.exitFee, trade.netPnl, trade.pnlPercent, trade.exitReason]))
  const comparisonItems = useMemo(() => [{ id: 'current', name: 'Current result', ...(result?.metrics || {}), strategy: result?.configuration.strategy }, ...saved.map((item) => ({ ...item, maximumDrawdown: item.maxDrawdown }))].filter((item) => item.strategy && selected.includes(item.id)), [result, saved, selected])
  const toggleCompare = (id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 3 ? [...current, id] : current)

  return <div className="space-y-6"><PageHeader description="Test deterministic long-only strategies against actual provider OHLC history." eyebrow="Historical simulation" title="Strategy Backtesting" />
    <div className="flex gap-3 rounded-xl border border-accent/25 bg-accent/5 p-4 text-xs leading-5 text-muted"><CircleAlert className="mt-0.5 size-4 shrink-0 text-accent" /><p>Backtests use historical data and simulated execution. Historical results do not guarantee future performance. Provider history may be limited; slippage is simulated, spread is not modeled, and same-candle SL/TP ordering assumes Stop Loss first.</p></div>
    <Card><div className="mb-5 flex items-center gap-2"><FlaskConical className="size-5 text-accent" /><div><h2 className="text-sm font-semibold">Backtest configuration</h2><p className="text-xs text-muted">One open position at a time. Signals execute at the next candle open.</p></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Select label="Market" onChange={update('symbol')} value={config.symbol}>{markets.map((item) => <option key={item.symbol} value={item.symbol}>{item.displaySymbol} · {item.category}</option>)}</Select><Select label="Interval" onChange={update('interval')} value={config.interval}>{intervals.map((item) => <option key={item} value={item}>{item}</option>)}</Select><Select label="Strategy" onChange={changeStrategy} value={config.strategy}>{Object.entries(STRATEGIES).map(([key, item]) => <option key={key} value={key}>{item.label}</option>)}</Select><Input hint="Independent from your TradePilot wallet." label="Backtest Capital (USD)" min="0.01" onChange={update('startingBalance')} step="any" type="number" value={config.startingBalance} />
      {config.strategy === 'ma' && <><Input label="Fast MA Period" min="2" onChange={updateParameter('fastPeriod')} step="1" type="number" value={config.strategyParameters.fastPeriod} /><Input label="Slow MA Period" min="3" onChange={updateParameter('slowPeriod')} step="1" type="number" value={config.strategyParameters.slowPeriod} /></>}
      {config.strategy === 'rsi' && <><Input label="RSI Period" min="2" onChange={updateParameter('rsiPeriod')} step="1" type="number" value={config.strategyParameters.rsiPeriod} /><Input label="Oversold Level" max="99" min="1" onChange={updateParameter('oversoldLevel')} step="any" type="number" value={config.strategyParameters.oversoldLevel} /><Input label="Exit Level" max="100" min="1" onChange={updateParameter('exitLevel')} step="any" type="number" value={config.strategyParameters.exitLevel} /></>}
      {config.strategy === 'breakout' && <><Input label="Lookback Period" min="2" onChange={updateParameter('lookbackPeriod')} step="1" type="number" value={config.strategyParameters.lookbackPeriod} /><Input label="Exit Lookback" min="2" onChange={updateParameter('exitLookback')} step="1" type="number" value={config.strategyParameters.exitLookback} /></>}
      <Select label="Position sizing" onChange={update('sizingMode')} value={config.sizingMode}><option value="percent">Fixed % of equity</option><option value="fixed">Fixed USD amount</option></Select><Input label={config.sizingMode === 'percent' ? 'Equity per trade (%)' : 'USD per trade'} max={config.sizingMode === 'percent' ? '100' : undefined} min="0.01" onChange={update('positionSize')} step="any" type="number" value={config.positionSize} /><Input label="Slippage (%)" max="5" min="0" onChange={update('slippage')} step="any" type="number" value={config.slippage} /><Input label="Stop Loss (%) · optional" max="100" min="0" onChange={update('stopLossPercent')} step="any" type="number" value={config.stopLossPercent} /><Input label="Take Profit (%) · optional" max="100" min="0" onChange={update('takeProfitPercent')} step="any" type="number" value={config.takeProfitPercent} /></div><div className="mt-5 flex flex-wrap items-center gap-3"><Button disabled={running} onClick={() => execute()}>{running && <LoaderCircle className="size-4 animate-spin" />}{running ? 'Loading history…' : 'Run Backtest'}</Button><p className="text-xs text-muted">Fee: {(TRADING_FEE_RATE * 100).toFixed(2)}% on entry and exit · maximum 500 candles</p></div>{error && <p className="mt-4 text-sm text-negative" role="alert">{error}</p>}{notice && <p className="mt-4 text-xs text-positive" role="status">{notice}</p>}</Card>
    {result && <><Card padding="none"><MarketReplay key={result.runId} market={marketBySymbol.get(result.configuration.symbol)} result={result} /></Card><Card padding="none"><BacktestEquityChart data={result.equityCurve} /></Card><Metrics result={result} />
      <Card padding="none"><div className="flex flex-col justify-between gap-3 border-b border-border px-5 py-4 sm:flex-row sm:items-center"><div><h2 className="text-sm font-semibold">Trade-by-trade results</h2><p className="mt-1 text-xs text-muted">Backtest-only executions; no Firestore trade records are created.</p></div><Button onClick={exportCsv} size="sm" variant="secondary"><Download className="size-4" />Export Backtest CSV</Button></div>{result.trades.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left"><thead className="border-b border-border bg-elevated/40 text-[10px] uppercase tracking-wider text-muted"><tr>{['#', 'Entry Date', 'Entry Price', 'Exit Date', 'Exit Price', 'Quantity', 'Net P/L', 'Return %', 'Fees', 'Exit Reason'].map((heading) => <th className="px-4 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{result.trades.map((trade, index) => <tr className="cursor-pointer hover:bg-elevated/40" key={`${trade.entryTime}-${index}`} onClick={() => setTradeDetail({ ...trade, number: index + 1 })}><td className="px-4 py-3 text-xs">{index + 1}</td><td className="px-4 py-3 text-xs">{dateTime(trade.entryTime)}</td><td className="financial-value px-4 py-3 text-xs">{formatPrice(trade.entryPrice, resultMarket)}</td><td className="px-4 py-3 text-xs">{dateTime(trade.exitTime)}</td><td className="financial-value px-4 py-3 text-xs">{formatPrice(trade.exitPrice, resultMarket)}</td><td className="financial-value px-4 py-3 text-xs">{trade.quantity.toFixed(6)}</td><td className={`financial-value px-4 py-3 text-xs ${trade.netPnl >= 0 ? 'text-positive' : 'text-negative'}`}>{formatCurrency(trade.netPnl)}</td><td className="financial-value px-4 py-3 text-xs">{trade.pnlPercent.toFixed(2)}%</td><td className="financial-value px-4 py-3 text-xs">{formatCurrency(trade.entryFee + trade.exitFee)}</td><td className="px-4 py-3"><Badge variant={trade.exitReason === 'Stop Loss' ? 'negative' : trade.exitReason === 'Take Profit' ? 'positive' : 'neutral'}>{trade.exitReason}</Badge></td></tr>)}</tbody></table></div> : <p className="p-8 text-center text-sm text-muted">No complete trades were generated by this configuration.</p>}</Card>
      <Card><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><Input className="flex-1" label="Save completed backtest" maxLength="80" onChange={(event) => setSaveName(event.target.value)} placeholder={`${resultMarket.displaySymbol} ${STRATEGIES[result.configuration.strategy].label}`} value={saveName} /><Button disabled={!saveName.trim()} onClick={save}><Save className="size-4" />Save summary</Button><label className="flex h-10 cursor-pointer items-center gap-2 text-xs text-muted"><input checked={selected.includes('current')} onChange={() => toggleCompare('current')} type="checkbox" />Compare current</label></div></Card></>}
    <SavedBacktests items={saved} onDelete={setDeleteTarget} onRerun={rerun} onSummary={setSummary} onToggle={toggleCompare} selected={selected} />
    {comparisonItems.length >= 2 && <Comparison items={comparisonItems} />}
    <TradeDetail market={resultMarket || market} onClose={() => setTradeDetail(null)} strategy={result?.configuration.strategy || config.strategy} trade={tradeDetail} />
    <Modal footer={<Button onClick={() => setSummary(null)} variant="secondary">Close</Button>} isOpen={Boolean(summary)} onClose={() => setSummary(null)} title={summary?.name || 'Saved backtest'}>{summary && <dl className="grid grid-cols-2 gap-4 text-sm">{[['Market', summary.symbol], ['Interval', summary.interval], ['Strategy', STRATEGIES[summary.strategy]?.label], ['Return', `${summary.returnPercent.toFixed(2)}%`], ['Net profit', formatCurrency(summary.netProfit)], ['Max drawdown', `${summary.maxDrawdown.toFixed(2)}%`], ['Win rate', `${summary.winRate.toFixed(2)}%`], ['Trades', summary.totalTrades]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted">{label}</dt><dd className="financial-value mt-1 font-semibold">{value}</dd></div>)}</dl>}</Modal>
    <Modal description="This removes only the saved summary. It does not affect your wallet or trading records." footer={<><Button onClick={() => setDeleteTarget(null)} variant="ghost">Cancel</Button><Button onClick={async () => { try { await deleteSavedBacktest(currentUser.uid, deleteTarget.id); setSelected((current) => current.filter((id) => id !== deleteTarget.id)); setDeleteTarget(null) } catch { setError('Unable to delete this saved backtest.') } }} variant="danger">Delete summary</Button></>} isOpen={Boolean(deleteTarget)} onClose={() => setDeleteTarget(null)} title={`Delete ${deleteTarget?.name || 'saved backtest'}?`} />
  </div>
}

function Metrics({ result }) { const metrics = result.metrics; const items = [['Starting balance', formatCurrency(metrics.startingBalance)], ['Ending balance', formatCurrency(metrics.endingBalance)], ['Net profit', formatCurrency(metrics.netProfit)], ['Return', `${metrics.returnPercent.toFixed(2)}%`], ['Total trades', metrics.totalTrades], ['Winning trades', metrics.winningTrades], ['Losing trades', metrics.losingTrades], ['Win rate', `${metrics.winRate.toFixed(2)}%`], ['Average win', formatCurrency(metrics.averageWin)], ['Average loss', formatCurrency(metrics.averageLoss)], ['Largest win', formatCurrency(metrics.largestWin)], ['Largest loss', formatCurrency(metrics.largestLoss)], ['Profit factor', factor(Number.isFinite(metrics.profitFactor) ? metrics.profitFactor : null)], ['Total fees', formatCurrency(metrics.totalFees)], ['Maximum drawdown', `${metrics.maximumDrawdown.toFixed(2)}%`], ['Average trade', formatCurrency(metrics.averageTrade)], ['Best trade', formatCurrency(metrics.bestTrade)], ['Worst trade', formatCurrency(metrics.worstTrade)], ['Candles tested', metrics.candlesTested]]; return <section aria-label="Backtest metrics" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-5">{items.map(([label, value]) => <Card key={label}><p className="text-xs text-muted">{label}</p><p className="financial-value mt-2 text-lg font-semibold">{value}</p></Card>)}</section> }
function SavedBacktests({ items, onDelete, onRerun, onSummary, onToggle, selected }) { return <Card padding="none"><div className="border-b border-border px-5 py-4"><h2 className="text-sm font-semibold">Saved Backtests</h2><p className="mt-1 text-xs text-muted">Summaries and configurations only; candle history is never stored. Run Again uses the provider's currently available history, so results may differ.</p></div>{items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="border-b border-border bg-elevated/40 text-[10px] uppercase tracking-wider text-muted"><tr>{['Compare', 'Name', 'Market', 'Interval', 'Strategy', 'Return', 'Win Rate', 'Max Drawdown', 'Trades', 'Created', 'Actions'].map((heading) => <th className="px-4 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{items.map((item) => <tr key={item.id}><td className="px-4 py-3"><input aria-label={`Compare ${item.name}`} checked={selected.includes(item.id)} disabled={!selected.includes(item.id) && selected.length >= 3} onChange={() => onToggle(item.id)} type="checkbox" /></td><td className="px-4 py-3 text-sm font-semibold">{item.name}</td><td className="px-4 py-3 text-xs">{item.symbol}</td><td className="px-4 py-3 text-xs">{item.interval}</td><td className="px-4 py-3 text-xs">{STRATEGIES[item.strategy]?.label}</td><td className={`financial-value px-4 py-3 text-xs ${item.returnPercent >= 0 ? 'text-positive' : 'text-negative'}`}>{item.returnPercent.toFixed(2)}%</td><td className="financial-value px-4 py-3 text-xs">{item.winRate.toFixed(2)}%</td><td className="financial-value px-4 py-3 text-xs">{item.maxDrawdown.toFixed(2)}%</td><td className="financial-value px-4 py-3 text-xs">{item.totalTrades}</td><td className="px-4 py-3 text-xs text-muted">{item.createdAt?.toDate?.().toLocaleDateString() || 'Just now'}</td><td className="px-4 py-3"><div className="flex gap-2"><Button onClick={() => onSummary(item)} size="sm" variant="ghost">View Summary</Button><Button onClick={() => onRerun(item)} size="sm" variant="secondary">Run Again</Button><Button aria-label={`Delete ${item.name}`} onClick={() => onDelete(item)} size="sm" variant="ghost"><Trash2 className="size-4" /></Button></div></td></tr>)}</tbody></table></div> : <p className="p-8 text-center text-sm text-muted">No saved backtests yet.</p>}</Card> }
function Comparison({ items }) { return <Card padding="none"><div className="border-b border-border px-5 py-4"><h2 className="text-sm font-semibold">Comparison</h2><p className="mt-1 text-xs text-muted">Historical comparison only—not a strategy recommendation.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left"><thead className="border-b border-border bg-elevated/40 text-[10px] uppercase text-muted"><tr>{['Result', 'Strategy', 'Return %', 'Net Profit', 'Win Rate', 'Profit Factor', 'Max Drawdown', 'Trades', 'Fees'].map((heading) => <th className="px-4 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{items.map((item) => <tr key={item.id}><td className="px-4 py-3 text-sm font-semibold">{item.name}</td><td className="px-4 py-3 text-xs">{STRATEGIES[item.strategy]?.label}</td><td className="financial-value px-4 py-3 text-xs">{item.returnPercent.toFixed(2)}%</td><td className="financial-value px-4 py-3 text-xs">{formatCurrency(item.netProfit)}</td><td className="financial-value px-4 py-3 text-xs">{item.winRate.toFixed(2)}%</td><td className="financial-value px-4 py-3 text-xs">{factor(item.profitFactor)}</td><td className="financial-value px-4 py-3 text-xs">{item.maximumDrawdown.toFixed(2)}%</td><td className="financial-value px-4 py-3 text-xs">{item.totalTrades}</td><td className="financial-value px-4 py-3 text-xs">{formatCurrency(item.totalFees)}</td></tr>)}</tbody></table></div></Card> }
function TradeDetail({ trade, onClose, market, strategy }) { const holding = trade ? trade.exitTime - trade.entryTime : 0; return <Modal footer={<Button onClick={onClose} variant="secondary">Close</Button>} isOpen={Boolean(trade)} onClose={onClose} title={trade ? `Backtest trade #${trade.number}` : 'Backtest trade'}>{trade && <dl className="grid grid-cols-2 gap-4 text-sm">{[['Market', market.displaySymbol], ['Strategy', STRATEGIES[strategy].label], ['Entry', `${dateTime(trade.entryTime)} · ${formatPrice(trade.entryPrice, market)}`], ['Exit', `${dateTime(trade.exitTime)} · ${formatPrice(trade.exitPrice, market)}`], ['Quantity', trade.quantity.toFixed(8)], ['Gross entry', formatCurrency(trade.entryGross)], ['Gross exit', formatCurrency(trade.exitGross)], ['Entry fee', formatCurrency(trade.entryFee)], ['Exit fee', formatCurrency(trade.exitFee)], ['Total fees', formatCurrency(trade.entryFee + trade.exitFee)], ['Net P/L', formatCurrency(trade.netPnl)], ['Return', `${trade.pnlPercent.toFixed(2)}%`], ['Holding period', `${Math.floor(holding / 3600)}h ${Math.floor(holding % 3600 / 60)}m`], ['Exit reason', trade.exitReason]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted">{label}</dt><dd className="financial-value mt-1 break-words font-semibold">{value}</dd></div>)}</dl>}</Modal> }
export default Backtest
