import { useEffect, useMemo, useRef, useState } from 'react'
import { BellPlus, CircleAlert, Radar, RefreshCw, Save, Star, Trash2 } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import Badge from '../components/common/Badge.jsx'
import Button from '../components/common/Button.jsx'
import Card from '../components/common/Card.jsx'
import Input from '../components/common/Input.jsx'
import PageHeader from '../components/common/PageHeader.jsx'
import SearchInput from '../components/common/SearchInput.jsx'
import Select from '../components/common/Select.jsx'
import MarketSourceBadge from '../components/trading/MarketSourceBadge.jsx'
import PriceAlertDialog from '../components/trading/PriceAlertDialog.jsx'
import PriceChange from '../components/trading/PriceChange.jsx'
import { markets } from '../data/markets.js'
import useAuth from '../hooks/useAuth.js'
import { getTicker, subscribeToTicker } from '../services/marketService.js'
import { analyzeScannerMarkets } from '../services/scannerService.js'
import { createScannerPreset, deleteScannerPreset, renameScannerPreset, subscribeToScannerPresets } from '../services/scannerPresetService.js'
import { addSymbol, removeSymbol, subscribeToWatchlist } from '../services/watchlistService.js'
import { getFirestoreErrorMessage } from '../utils/firestoreErrors.js'
import { formatPrice } from '../utils/marketFormatters.js'
import { buildScannerRow } from '../utils/scannerAnalysis.js'

const modes = [['momentum', 'Momentum'], ['trend', 'Trend'], ['volatility', 'Volatility'], ['breakout', 'Breakout'], ['movers', 'Gainers / Losers'], ['watchlist', 'Watchlist']]
const initialControls = { mode: 'momentum', interval: '1h', marketType: 'all', trend: 'all', minChange: '', minMomentum: '', minVolatility: '', sortBy: 'scannerScore', sortDirection: 'desc' }
const sortForMode = { momentum: 'momentum', trend: 'scannerScore', volatility: 'volatility', breakout: 'breakoutDistance', movers: 'changePercent', watchlist: 'scannerScore' }
const valueFor = (row, field) => field === 'price' ? row.ticker?.price : field === 'volatility' ? row.analysis?.volatility : field === 'breakoutDistance' ? row.analysis?.breakoutDistance : row[field]
const typeFor = (market) => market.symbol === 'XAUUSD' ? 'gold' : market.type
const metric = (value, suffix = '%') => Number.isFinite(value) ? `${value >= 0 ? '+' : ''}${value.toFixed(2)}${suffix}` : 'Analyzing'

function Screener() {
  const { currentUser } = useAuth(); const navigate = useNavigate(); const scanToken = useRef(0)
  const [controls, setControls] = useState(initialControls), [search, setSearch] = useState(''), [tickers, setTickers] = useState(new Map()), [analysis, setAnalysis] = useState(new Map())
  const [watchlist, setWatchlist] = useState([]), [presets, setPresets] = useState([]), [unavailable, setUnavailable] = useState(new Set()), [scanning, setScanning] = useState(true), [error, setError] = useState(''), [pending, setPending] = useState(''), [alertMarket, setAlertMarket] = useState(null), [notice, setNotice] = useState('')

  useEffect(() => subscribeToWatchlist(currentUser.uid, (item) => setWatchlist(item?.symbols || []), (requestError) => setError(getFirestoreErrorMessage(requestError))), [currentUser.uid])
  useEffect(() => subscribeToScannerPresets(currentUser.uid, setPresets, () => setError('Scanner presets require the latest Firestore rules and index.')), [currentUser.uid])
  useEffect(() => {
    let active = true
    Promise.allSettled(markets.filter((market) => market.type === 'crypto').map((market) => getTicker(market.symbol))).then((results) => { if (!active) return; const fulfilled = results.filter((result) => result.status === 'fulfilled').map((result) => result.value); setTickers((current) => new Map([...current, ...fulfilled.map((ticker) => [ticker.symbol, ticker])])) })
    const stops = markets.map((market) => subscribeToTicker(market.symbol, (ticker) => { setTickers((current) => new Map(current).set(market.symbol, ticker)); setUnavailable((current) => { const next = new Set(current); next.delete(market.symbol); return next }) }, () => setUnavailable((current) => new Set(current).add(market.symbol)), () => {}))
    return () => { active = false; stops.forEach((stop) => stop()) }
  }, [])
  useEffect(() => {
    const token = ++scanToken.current
    analyzeScannerMarkets({ markets, interval: initialControls.interval, tickers: new Map(), onResult: (item) => setAnalysis((current) => new Map(current).set(item.symbol, item)), isCancelled: () => token !== scanToken.current }).finally(() => { if (token === scanToken.current) setScanning(false) })
    return () => { scanToken.current += 1 }
  }, [])

  const runAnalysis = async () => {
    const token = ++scanToken.current; setScanning(true); setNotice(''); setError(''); setAnalysis(new Map(markets.map((market) => [market.symbol, { symbol: market.symbol, state: 'pending' }])))
    await analyzeScannerMarkets({ markets, interval: controls.interval, tickers, force: true, onResult: (item) => setAnalysis((current) => new Map(current).set(item.symbol, item)), isCancelled: () => token !== scanToken.current })
    if (token === scanToken.current) { setScanning(false); setNotice('Historical scanner analysis refreshed.') }
  }
  const rows = useMemo(() => markets.map((market) => { const item = analysis.get(market.symbol); return { ...buildScannerRow(market, tickers.get(market.symbol), item?.analysis, item?.state || 'pending'), quoteUnavailable: unavailable.has(market.symbol) } }), [analysis, tickers, unavailable])
  const visible = useMemo(() => rows.filter((row) => {
    const watched = watchlist.includes(row.symbol), query = `${row.symbol} ${row.displaySymbol} ${row.name}`.toLowerCase()
    const filters = controls.marketType === 'all' || typeFor(row) === controls.marketType
    const trend = controls.trend === 'all' || row.analysis?.trend === controls.trend
    const minimum = (field, value) => value === '' || value === null || (Number.isFinite(field) && field >= Number(value))
    return (controls.mode !== 'watchlist' || watched) && filters && trend && query.includes(search.toLowerCase()) && minimum(row.changePercent, controls.minChange) && minimum(row.momentum, controls.minMomentum) && minimum(row.analysis?.volatility, controls.minVolatility)
  }).sort((first, second) => { const a = valueFor(first, controls.sortBy), b = valueFor(second, controls.sortBy); if (!Number.isFinite(a)) return Number.isFinite(b) ? 1 : 0; if (!Number.isFinite(b)) return -1; return controls.sortDirection === 'asc' ? a - b : b - a }), [controls, rows, search, watchlist])
  const ranked = rows.filter((row) => row.analysisState === 'ready'), availableTickers = rows.filter((row) => Number.isFinite(row.changePercent))
  const highest = (field) => [...ranked].filter((row) => Number.isFinite(valueFor(row, field))).sort((a, b) => valueFor(b, field) - valueFor(a, field))[0]
  const closestBreakout = [...ranked].filter((row) => Number.isFinite(row.analysis?.breakoutDistance)).sort((a, b) => Math.abs(a.analysis.breakoutDistance) - Math.abs(b.analysis.breakoutDistance))[0]
  const opportunities = [['Strongest Momentum', highest('momentum'), 'momentum'], ['Highest Volatility', highest('volatility'), 'volatility'], ['Closest Breakout', closestBreakout, 'breakoutDistance'], ['Largest Gainer', [...availableTickers].filter((row) => row.changePercent > 0).sort((a, b) => b.changePercent - a.changePercent)[0], 'changePercent']]
  const toggleWatch = async (symbol) => { setPending(symbol); try { await (watchlist.includes(symbol) ? removeSymbol(currentUser.uid, symbol) : addSymbol(currentUser.uid, symbol)) } catch (requestError) { setError(getFirestoreErrorMessage(requestError)) } finally { setPending('') } }
  const update = (field) => (event) => setControls((current) => ({ ...current, [field]: event.target.value }))
  const selectMode = (event) => { const mode = event.target.value; setControls((current) => ({ ...current, mode, sortBy: sortForMode[mode], sortDirection: 'desc' })) }
  const applyPreset = (preset) => { if (preset.interval !== controls.interval) { scanToken.current += 1; setScanning(false); setAnalysis(new Map()) } setControls({ mode: preset.mode, interval: preset.interval, marketType: preset.marketType, trend: preset.trend, minChange: preset.minChange ?? '', minMomentum: preset.minMomentum ?? '', minVolatility: preset.minVolatility ?? '', sortBy: preset.sortBy, sortDirection: preset.sortDirection }); setNotice(`Applied ${preset.name}. Refresh to analyze the selected interval.`) }

  return <div className="space-y-6"><PageHeader actions={<Button disabled={scanning} onClick={runAnalysis} variant="secondary"><RefreshCw className={`size-4 ${scanning ? 'animate-spin' : ''}`} />{scanning ? 'Analyzing…' : 'Refresh analysis'}</Button>} description="Rank live markets with transparent historical indicators. Scanner results are informational only." eyebrow="Market intelligence" title="Market Screener" />
    {error && <div className="flex gap-2 rounded-lg border border-negative/25 bg-negative/10 p-3 text-sm text-negative" role="alert"><CircleAlert className="size-4 shrink-0" />{error}</div>}{notice && <p className="rounded-lg border border-positive/20 bg-positive/5 px-4 py-3 text-xs text-positive" role="status">{notice}</p>}
    <Card><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><Select label="Scanner mode" onChange={selectMode} value={controls.mode}>{modes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Select label="Analysis interval" onChange={(event) => { scanToken.current += 1; setScanning(false); setAnalysis(new Map()); update('interval')(event); setNotice('Interval changed. Refresh to load its historical analysis.') }} value={controls.interval}>{['15m', '1h', '4h', '1d'].map((value) => <option key={value}>{value}</option>)}</Select><Select label="Market type" onChange={update('marketType')} value={controls.marketType}><option value="all">All</option><option value="crypto">Crypto</option><option value="forex">Forex</option><option value="gold">Gold</option></Select><Select label="Trend" onChange={update('trend')} value={controls.trend}><option value="all">All</option><option>Bullish</option><option>Bearish</option><option>Neutral</option></Select><Select label="Sort by" onChange={update('sortBy')} value={controls.sortBy}><option value="scannerScore">Scanner score</option><option value="price">Price</option><option value="changePercent">24h change</option><option value="momentum">Momentum</option><option value="volatility">Volatility</option><option value="breakoutDistance">Breakout distance</option></Select><Select label="Direction" onChange={update('sortDirection')} value={controls.sortDirection}><option value="desc">Highest first</option><option value="asc">Lowest first</option></Select><SearchInput aria-label="Search scanner markets" className="sm:col-span-2" onChange={(event) => setSearch(event.target.value)} placeholder="Search symbol or name" value={search} /><Input label="Minimum 24h change %" max="100" min="-100" onChange={update('minChange')} step="any" type="number" value={controls.minChange} /><Input label="Minimum momentum" max="100" min="-100" onChange={update('minMomentum')} step="any" type="number" value={controls.minMomentum} /><Input label="Minimum volatility %" max="100" min="0" onChange={update('minVolatility')} step="any" type="number" value={controls.minVolatility} /></div><p className="mt-4 text-[10px] leading-4 text-muted">Scanner Score = Momentum + Trend Score (+2 bullish, −2 bearish) + capped Breakout Proximity Score. It is a transparent ranking aid, not a recommendation.</p></Card>
    <section aria-label="Opportunity summary" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{opportunities.map(([label, row, field]) => <Card key={label}><p className="text-xs text-muted">Opportunity · {label}</p>{row ? <><div className="mt-3 flex items-center justify-between gap-3"><p className="text-lg font-semibold">{row.displaySymbol}</p><Badge variant="neutral">{typeFor(row)}</Badge></div><p className="financial-value mt-2 text-sm text-accent">{field === 'volatility' ? metric(row.analysis?.volatility) : field === 'breakoutDistance' ? metric(row.analysis?.breakoutDistance) : metric(row[field])}</p><p className="financial-value mt-1 text-xs text-muted">{formatPrice(row.ticker?.price, row)}</p><Button className="mt-4" onClick={() => navigate(`/trade?symbol=${row.symbol}`)} size="sm" variant="secondary">Open Trade</Button></> : <p className="mt-4 text-sm text-muted">Waiting for available data.</p>}</Card>)}</section>
    <div className="grid gap-4 lg:grid-cols-2"><MoverCard rows={[...availableTickers].filter((row) => row.changePercent > 0).sort((a, b) => b.changePercent - a.changePercent).slice(0, 3)} title="Top Gainers" /><MoverCard rows={[...availableTickers].filter((row) => row.changePercent < 0).sort((a, b) => a.changePercent - b.changePercent).slice(0, 3)} title="Top Losers" /></div>
    <Card padding="none"><div className="flex flex-col justify-between gap-3 border-b border-border p-4 sm:flex-row sm:items-center"><div><h2 className="text-sm font-semibold">Scanner results</h2><p className="mt-1 text-xs text-muted">{visible.length} markets · live quote fields update without refetching history</p></div>{scanning && <Badge variant="warning">Progressive analysis running</Badge>}</div>{visible.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1280px] text-left"><thead className="border-b border-border bg-elevated/40 text-[10px] uppercase tracking-wider text-muted"><tr>{['Market', 'Type', 'Price', '24h Change', 'Trend', 'Momentum', 'Volatility', 'Breakout', 'Source', 'Actions'].map((heading) => <th className="px-4 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{visible.map((row) => <ScannerRow currentUser={currentUser} key={row.symbol} onAlert={setAlertMarket} onToggleWatch={toggleWatch} onTrade={() => navigate(`/trade?symbol=${row.symbol}`)} pending={pending} row={row} watched={watchlist.includes(row.symbol)} />)}</tbody></table></div> : <div className="grid min-h-48 place-items-center p-8 text-center"><div><Radar className="mx-auto size-6 text-muted" /><h2 className="mt-3 text-sm font-semibold">{controls.mode === 'watchlist' && !watchlist.length ? 'Your watchlist is empty' : 'No symbols match these filters'}</h2><p className="mt-1 text-xs text-muted">Adjust the scanner mode or filter thresholds.</p></div></div>}</Card>
    <ScannerPresets controls={controls} items={presets} onApply={applyPreset} onError={setError} userId={currentUser.uid} />
    {alertMarket && <PriceAlertDialog currentPrice={alertMarket.ticker?.price} initialCondition="above" initialTarget={['Breakout', 'Near Breakout'].includes(alertMarket.analysis?.breakoutStatus) ? alertMarket.analysis.breakoutLevel : ''} key={alertMarket.symbol} market={alertMarket} onClose={() => setAlertMarket(null)} onCreated={() => setNotice(`Price alert created for ${alertMarket.displaySymbol}.`)} userId={currentUser.uid} />}
  </div>
}

function ScannerRow({ row, watched, pending, onToggleWatch, onTrade, onAlert }) { const trend = row.analysis?.trend; const status = row.analysisState === 'pending' ? 'Analyzing' : row.analysisState === 'insufficient' ? 'Insufficient history' : row.analysisState === 'unavailable' ? 'Unavailable' : row.analysis?.breakoutStatus; return <tr><td className="px-4 py-4"><p className="text-sm font-semibold">{row.displaySymbol}</p><p className="text-xs text-muted">{row.name}</p></td><td className="px-4 py-4 text-xs capitalize">{typeFor(row)}</td><td className="px-4 py-4"><p className="financial-value text-sm">{formatPrice(row.ticker?.price, row)}</p>{row.type === 'forex' && <p className="mt-1 text-[10px] text-muted">{row.ticker?.marketStatus || (row.quoteUnavailable ? 'Quote unavailable' : 'Waiting for quote')}</p>}</td><td className="px-4 py-4">{Number.isFinite(row.changePercent) ? <PriceChange value={row.changePercent} /> : <span className="text-xs text-muted">{row.quoteUnavailable ? 'Unavailable' : 'No quote yet'}</span>}</td><td className="px-4 py-4"><Badge variant={trend === 'Bullish' ? 'positive' : trend === 'Bearish' ? 'negative' : 'neutral'}>{trend || status}</Badge>{row.analysis && <p className="financial-value mt-1 text-[10px] text-muted">{row.analysis.fastMA?.toFixed(5) || '—'} / {row.analysis.slowMA?.toFixed(5) || '—'}</p>}</td><td className="px-4 py-4"><p className="financial-value text-xs font-semibold">{metric(row.momentum, '')}</p>{row.analysis && <p className="mt-1 text-[10px] text-muted">24h {metric(row.changePercent)} · recent {metric(row.analysis.recentReturn)}</p>}</td><td className="px-4 py-4"><p className="financial-value text-xs font-semibold">{metric(row.analysis?.volatility)}</p>{row.analysis && <p className="financial-value mt-1 text-[10px] text-muted">ATR {formatPrice(row.analysis.atr, row)}</p>}</td><td className="px-4 py-4"><p className="text-xs font-semibold">{status}</p>{row.analysis && <p className="financial-value mt-1 text-[10px] text-muted">{formatPrice(row.analysis.breakoutLevel, row)} · {metric(row.analysis.breakoutDistance)}</p>}</td><td className="px-4 py-4"><MarketSourceBadge status={row.quoteUnavailable ? 'unavailable' : row.ticker?.connectionStatus || 'connecting'} type={row.type} /></td><td className="px-4 py-4"><div className="flex gap-1"><Button onClick={onTrade} size="sm" variant="secondary">Open Trade</Button><Button aria-label={`Create ${row.displaySymbol} alert`} onClick={() => onAlert(row)} size="sm" variant="ghost"><BellPlus className="size-4" /></Button><Button aria-label={`${watched ? 'Remove' : 'Add'} ${row.displaySymbol} ${watched ? 'from' : 'to'} watchlist`} disabled={pending === row.symbol} onClick={() => onToggleWatch(row.symbol)} size="sm" variant="ghost"><Star className={`size-4 ${watched ? 'fill-current text-warning' : ''}`} /></Button></div></td></tr> }
function MoverCard({ title, rows }) { return <Card padding="none"><div className="border-b border-border px-5 py-4"><h2 className="text-sm font-semibold">{title}</h2></div><div className="divide-y divide-border">{rows.length ? rows.map((row) => <div className="flex items-center justify-between gap-4 px-5 py-3" key={row.symbol}><span className="text-sm font-semibold">{row.displaySymbol}</span><PriceChange value={row.changePercent} /></div>) : <p className="p-6 text-center text-xs text-muted">No live change data.</p>}</div></Card> }
function ScannerPresets({ controls, items, onApply, onError, userId }) { const [name, setName] = useState(''); const save = async () => { try { await createScannerPreset(userId, { ...controls, name }); setName('') } catch (error) { onError(getFirestoreErrorMessage(error)) } }; return <Card><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><Input className="flex-1" label="Save Current Screener" maxLength="80" onChange={(event) => setName(event.target.value)} placeholder="Momentum watch" value={name} /><Button disabled={!name.trim()} onClick={save}><Save className="size-4" />Save preset</Button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article className="rounded-lg border border-border bg-elevated/40 p-3" key={item.id}><input aria-label="Preset name" className="w-full bg-transparent text-sm font-semibold outline-none focus:text-accent" defaultValue={item.name} onBlur={(event) => { if (event.target.value.trim() !== item.name) renameScannerPreset(item.id, event.target.value).catch((error) => onError(getFirestoreErrorMessage(error))) }} /><p className="mt-1 text-[10px] capitalize text-muted">{item.mode} · {item.interval} · {item.marketType} · {item.trend}</p><div className="mt-3 flex gap-2"><Button onClick={() => onApply(item)} size="sm" variant="secondary">Apply</Button><Button aria-label={`Delete ${item.name}`} onClick={() => deleteScannerPreset(item.id).catch((error) => onError(getFirestoreErrorMessage(error)))} size="sm" variant="ghost"><Trash2 className="size-4" /></Button></div></article>)}</div>{!items.length && <p className="mt-5 text-xs text-muted">No scanner presets saved.</p>}<p className="mt-4 text-[10px] text-muted">Applying a preset changes filters only. It never creates alerts or orders.</p></Card> }
export default Screener
