import { useState } from 'react'
import { CheckCircle2, CircleAlert, KeyRound, LoaderCircle, LockKeyhole, Mail, ShieldCheck, Smartphone } from 'lucide-react'
import Button from '../components/common/Button.jsx'
import Card from '../components/common/Card.jsx'
import Input from '../components/common/Input.jsx'
import PageHeader from '../components/common/PageHeader.jsx'
import useAuth from '../hooks/useAuth.js'
import { changePassword } from '../services/authService.js'
import { getFirebaseErrorMessage } from '../utils/firebaseErrors.js'

function Security() {
  const { currentUser, resetPassword } = useAuth()
  const [form, setForm] = useState({ current: '', next: '', confirm: '' }); const [processing, setProcessing] = useState(false); const [resetting, setResetting] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const update = (field) => (event) => { setForm((current) => ({ ...current, [field]: event.target.value })); setError(''); setSuccess('') }
  const submit = async (event) => { event.preventDefault(); setError(''); setSuccess(''); if (form.next.length < 8) return setError('Use at least 8 characters for the new password.'); if (form.next !== form.confirm) return setError('New password confirmation does not match.'); setProcessing(true); try { await changePassword(form.current, form.next); setForm({ current: '', next: '', confirm: '' }); setSuccess('Password changed successfully.') } catch (requestError) { setError(requestError?.code === 'auth/invalid-credential' ? 'The current password is incorrect.' : getFirebaseErrorMessage(requestError)) } finally { setProcessing(false) } }
  const sendReset = async () => { setError(''); setSuccess(''); setResetting(true); try { await resetPassword(currentUser.email); setSuccess('Password reset email requested. Check your inbox.') } catch (requestError) { setError(getFirebaseErrorMessage(requestError)) } finally { setResetting(false) } }
  return <div className="space-y-6"><PageHeader description="Manage password access and review the authentication protections available for your account." eyebrow="Account" title="Security" />{error && <div className="flex max-w-3xl gap-2 rounded-lg border border-negative/25 bg-negative/10 p-3 text-sm text-negative" role="alert"><CircleAlert className="size-4" />{error}</div>}{success && <div className="flex max-w-3xl gap-2 rounded-lg border border-positive/25 bg-positive/10 p-3 text-sm text-positive" role="status"><CheckCircle2 className="size-4" />{success}</div>}
    <div className="grid max-w-5xl gap-4 lg:grid-cols-2"><Card padding="lg"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-accent/10 text-accent"><KeyRound className="size-5" /></span><div><h2 className="text-sm font-semibold">Change password</h2><p className="mt-1 text-xs text-muted">Requires your current password for recent authentication.</p></div></div><form className="mt-6 grid gap-4" onSubmit={submit}><Input autoComplete="current-password" label="Current password" onChange={update('current')} type="password" value={form.current} /><Input autoComplete="new-password" hint="Use at least 8 characters." label="New password" onChange={update('next')} type="password" value={form.next} /><Input autoComplete="new-password" label="Confirm new password" onChange={update('confirm')} type="password" value={form.confirm} /><Button disabled={processing} type="submit">{processing && <LoaderCircle className="size-4 animate-spin" />}{processing ? 'Changing…' : 'Change password'}</Button></form></Card>
      <div className="space-y-4"><Card><Mail className="size-5 text-accent" /><h2 className="mt-4 text-sm font-semibold">Password reset</h2><p className="mt-2 text-xs leading-5 text-muted">Send Firebase password recovery instructions to {currentUser?.email}.</p><Button className="mt-4" disabled={resetting} onClick={sendReset} size="sm" variant="secondary">{resetting ? 'Sending…' : 'Send reset email'}</Button></Card><Card><Smartphone className="size-5 text-muted" /><div className="mt-4 flex items-center justify-between gap-3"><h2 className="text-sm font-semibold">Two-factor authentication</h2><span className="rounded-full bg-elevated px-2.5 py-1 text-[10px] font-semibold text-muted">Not configured</span></div><p className="mt-2 text-xs leading-5 text-muted">Multi-factor authentication is not implemented in this TradePilot phase. There is no inactive toggle.</p></Card></div></div>
    <Card className="max-w-5xl"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-positive" /><div><h2 className="text-sm font-semibold">Authentication information</h2><dl className="mt-4 grid gap-4 text-xs sm:grid-cols-3"><div><dt className="text-muted">Authenticated account</dt><dd className="mt-1 font-semibold">Signed in</dd></div><div><dt className="text-muted">Email</dt><dd className="mt-1 break-all font-semibold">{currentUser?.email}</dd></div><div><dt className="text-muted">Security provider</dt><dd className="mt-1 flex items-center gap-1.5 font-semibold"><LockKeyhole className="size-3.5" />{currentUser?.providerData?.[0]?.providerId || 'password'}</dd></div></dl><p className="mt-4 text-xs leading-5 text-muted">TradePilot does not claim remote session management. Sign out on devices you no longer use.</p></div></div></Card>
  </div>
}
export default Security
