import { useEffect, useState } from 'react'
import { BookmarkPlus, Trash2 } from 'lucide-react'
import { createOrderPreset, deleteOrderPreset, renameOrderPreset, subscribeToOrderPresets } from '../../services/orderPresetService.js'
import Button from '../common/Button.jsx'
import Input from '../common/Input.jsx'
import Modal from '../common/Modal.jsx'

function OrderPresets({ userId, setup, onApply }) {
  const [presets, setPresets] = useState([]), [open, setOpen] = useState(false), [name, setName] = useState(''), [trailing, setTrailing] = useState(''), [error, setError] = useState('')
  useEffect(() => subscribeToOrderPresets(userId, setPresets, () => setError('Saved presets are unavailable.')), [userId])
  const save = async () => { setError(''); try { await createOrderPreset(userId, { name, riskPercent: setup.riskPercent || 2, stopLossPercent: setup.stopLossPercent, takeProfitRatio: setup.takeProfitRatio, trailingStopPercent: trailing === '' ? null : Number(trailing) }); setName(''); setTrailing('') } catch (requestError) { setError(requestError.message) } }
  return <><Button fullWidth onClick={() => setOpen(true)} size="sm" variant="secondary"><BookmarkPlus className="size-4" />Saved Presets</Button><Modal footer={<Button onClick={() => setOpen(false)} variant="secondary">Done</Button>} isOpen={open} onClose={() => setOpen(false)} title="Simulation Presets"><div className="space-y-5"><div className="grid grid-cols-2 gap-3"><Input label="Preset name" maxLength="80" onChange={(event) => setName(event.target.value)} placeholder="Conservative" value={name} /><Input label="Trailing stop % (optional)" max="25" min="0" onChange={(event) => setTrailing(event.target.value)} step="any" type="number" value={trailing} /></div><Button disabled={!name.trim()} fullWidth onClick={save} size="sm">Save Current Setup</Button>{error && <p className="text-xs text-negative">{error}</p>}<div className="space-y-2 border-t border-border pt-4">{presets.length ? presets.map((preset) => <div className="flex flex-col gap-3 rounded-lg bg-surface p-3 sm:flex-row sm:items-center" key={preset.id}><div className="min-w-0 flex-1"><input aria-label="Preset name" className="w-full bg-transparent text-sm font-semibold outline-none focus:text-accent" defaultValue={preset.name} onBlur={(event) => { if (event.target.value.trim() !== preset.name) renameOrderPreset(preset.id, event.target.value).catch(() => setError('Could not rename preset.')) }} /><p className="mt-1 text-[10px] text-muted">Risk {preset.riskPercent}% · SL {preset.stopLossPercent ?? '—'}% · R:R {preset.takeProfitRatio ?? '—'} · Trail {preset.trailingStopPercent ?? '—'}%</p></div><div className="flex gap-2"><Button onClick={() => { onApply(preset); setOpen(false) }} size="sm" variant="secondary">Apply</Button><Button aria-label={`Delete ${preset.name}`} onClick={() => deleteOrderPreset(preset.id).catch(() => setError('Could not delete preset.'))} size="sm" variant="ghost"><Trash2 className="size-4" /></Button></div></div>) : <p className="py-4 text-center text-xs text-muted">No saved presets yet.</p>}</div><p className="text-[10px] text-muted">Applying a preset fills compatible inputs only and never submits an order.</p></div></Modal></>
}
export default OrderPresets
