import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, LoaderCircle, Pencil, ShieldAlert, Trash2, UserCog } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import Badge from '../../components/common/Badge.jsx'
import Button from '../../components/common/Button.jsx'
import Card from '../../components/common/Card.jsx'
import Modal from '../../components/common/Modal.jsx'
import PageHeader from '../../components/common/PageHeader.jsx'
import useAuth from '../../hooks/useAuth.js'
import { createAdminNote, deleteAdminNote, getAdminUserDetails, subscribeToAdminNotes, updateAdminNote, updateUserRole, updateUserStatus } from '../../services/adminService.js'
import { formatAdminDate, statusVariant } from '../../utils/adminFormatters.js'
import { formatCurrency } from '../../utils/formatCurrency.js'
import { getFirestoreErrorMessage } from '../../utils/firestoreErrors.js'

export default function UserDetail() {
  const { userId } = useParams(), { currentUser } = useAuth()
  const [data, setData] = useState(null), [notes, setNotes] = useState([]), [note, setNote] = useState(''), [edit, setEdit] = useState(null), [confirm, setConfirm] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const load = useCallback(() => getAdminUserDetails(userId).then(setData).catch((e) => setError(getFirestoreErrorMessage(e))), [userId])
  useEffect(() => { load(); return subscribeToAdminNotes(userId, setNotes, (e) => setError(getFirestoreErrorMessage(e))) }, [load, userId])
  const act = async () => { if (!confirm) return; setBusy(true); setError(''); try { if (confirm.type === 'role') await updateUserRole(userId, confirm.value); else if (confirm.type === 'status') await updateUserStatus(userId, confirm.value); else if (confirm.type === 'delete-note') await deleteAdminNote(confirm.noteId); setConfirm(null); await load() } catch (e) { setError(getFirestoreErrorMessage(e)) } finally { setBusy(false) } }
  const saveNote = async () => { setBusy(true); setError(''); try { if (edit) await updateAdminNote(edit.id, note); else await createAdminNote(userId, note); setNote(''); setEdit(null) } catch (e) { setError(getFirestoreErrorMessage(e)) } finally { setBusy(false) } }
  if (!data) return <div className="space-y-6"><Link className="inline-flex items-center gap-2 text-sm text-accent" to="/admin/users"><ArrowLeft className="size-4" />Back to users</Link><Card><p className="text-sm text-muted">{error || 'Loading user details…'}</p></Card></div>
  const { profile, wallet, metrics } = data, self = currentUser.uid === userId
  const cards = [['Wallet balance', formatCurrency(wallet?.availableBalance || 0)], ['Account equity', formatCurrency(metrics.accountEquity)], ['Open positions', metrics.openPositions], ['Open exposure', formatCurrency(metrics.openExposure)], ['Realized P/L', formatCurrency(metrics.realizedPnl)], ['Unrealized P/L', formatCurrency(metrics.unrealizedPnl)], ['Trade count', metrics.totalTrades], ['Active orders', metrics.pendingOrders], ['Pending deposits', metrics.pendingDeposits], ['Pending withdrawals', metrics.pendingWithdrawals], ['Risk protection', metrics.riskProtectionEnabled ? 'Enabled' : 'Disabled']]
  return <div className="space-y-6"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-accent" to="/admin/users"><ArrowLeft className="size-4" />Back to users</Link><PageHeader eyebrow="User operations" title={profile.fullName || 'Unnamed user'} description={profile.email} actions={!self && <div className="flex flex-wrap gap-2"><Button onClick={() => setConfirm({ type: 'role', value: profile.role === 'admin' ? 'user' : 'admin' })} variant="secondary"><UserCog className="size-4" />Change role</Button><Button onClick={() => setConfirm({ type: 'status', value: profile.accountStatus === 'suspended' ? 'active' : 'suspended' })} variant={profile.accountStatus === 'suspended' ? 'success' : 'danger'}><ShieldAlert className="size-4" />{profile.accountStatus === 'suspended' ? 'Reactivate' : 'Suspend'}</Button></div>} />
    {error && <div className="rounded-lg border border-negative/25 bg-negative/10 px-4 py-3 text-sm text-negative">{error}</div>}
    <Card><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted">User ID</p><p className="mt-1 break-all font-mono text-xs">{userId}</p></div><div><p className="text-xs text-muted">Role</p><p className="mt-2"><Badge variant={profile.role === 'admin' ? 'warning' : 'neutral'}>{profile.role}</Badge></p></div><div><p className="text-xs text-muted">Status</p><p className="mt-2"><Badge variant={statusVariant(profile.accountStatus)}>{profile.accountStatus}</Badge></p></div><div><p className="text-xs text-muted">Joined</p><p className="mt-1 text-sm">{formatAdminDate(profile.createdAt)}</p></div></div>{self && <p className="mt-4 text-xs text-warning">For safety, you cannot change your own role or account status.</p>}</Card>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label, value]) => <Card key={label}><p className="text-xs text-muted">{label}</p><p className="financial-value mt-3 text-xl font-semibold">{value}</p></Card>)}</div>
    <Card><h2 className="text-sm font-semibold">Administrative notes</h2><p className="mt-1 text-xs text-muted">Private operational context stored separately from the user profile.</p><textarea className="mt-4 min-h-28 w-full resize-y rounded-lg border border-border bg-elevated px-3 py-2 text-sm outline-none focus:border-accent" maxLength={2000} onChange={(e) => setNote(e.target.value)} placeholder="Add a private admin note…" value={note} /><div className="mt-3 flex gap-2"><Button disabled={busy || !note.trim()} onClick={saveNote}>{busy && <LoaderCircle className="size-4 animate-spin" />}{edit ? 'Update note' : 'Add note'}</Button>{edit && <Button onClick={() => { setEdit(null); setNote('') }} variant="ghost">Cancel edit</Button>}</div><div className="mt-5 divide-y divide-border">{notes.length === 0 ? <p className="py-5 text-sm text-muted">No notes for this user.</p> : notes.map((item) => <article className="py-4" key={item.id}><p className="whitespace-pre-wrap text-sm leading-6">{item.note}</p><div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-muted"><span>{formatAdminDate(item.createdAt)}</span><span className="font-mono">{item.adminUserId}</span><button className="inline-flex cursor-pointer items-center gap-1 text-accent" onClick={() => { setEdit(item); setNote(item.note) }}><Pencil className="size-3" />Edit</button><button className="inline-flex cursor-pointer items-center gap-1 text-negative" onClick={() => setConfirm({ type: 'delete-note', noteId: item.id })}><Trash2 className="size-3" />Delete</button></div></article>)}</div></Card>
    <Modal isOpen={Boolean(confirm)} onClose={() => !busy && setConfirm(null)} title={confirm?.type === 'delete-note' ? 'Delete admin note?' : 'Confirm account change'} description={confirm?.type === 'role' ? `Change this user to ${confirm.value}?` : confirm?.type === 'status' ? `${confirm.value === 'suspended' ? 'Suspend' : 'Reactivate'} this account?` : 'This private note will be permanently removed.'} footer={<><Button disabled={busy} onClick={() => setConfirm(null)} variant="ghost">Cancel</Button><Button disabled={busy} onClick={act} variant={confirm?.value === 'active' ? 'success' : 'danger'}>{busy && <LoaderCircle className="size-4 animate-spin" />}Confirm</Button></>}><p className="text-sm leading-6 text-muted">The action takes effect immediately and sensitive account changes are written to the audit log.</p></Modal>
  </div>
}
